// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WebAndLoadTestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.22609.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UITutorialHighFrequencWindow.UIItemGroup.UIAddressandsearchbarEdit;
            WinClient uIItem590AAAA2739E485eClient = this.UIItem590AAAA2739E485eWindow.UIItem590AAAA2739E485eClient;
            #endregion

            // Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, new Point(331, 16));

            // Type 'www.hsd.com.a{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.RecordedMethod1Params.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);

            // Click '{590AAAA2-739E-485e-BF4D-08DDD39C93F6}' client
            Mouse.Click(uIItem590AAAA2739E485eClient, new Point(297, 13));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UITutorialHighFrequencWindow UITutorialHighFrequencWindow
        {
            get
            {
                if ((this.mUITutorialHighFrequencWindow == null))
                {
                    this.mUITutorialHighFrequencWindow = new UITutorialHighFrequencWindow();
                }
                return this.mUITutorialHighFrequencWindow;
            }
        }
        
        public UIItem590AAAA2739E485eWindow UIItem590AAAA2739E485eWindow
        {
            get
            {
                if ((this.mUIItem590AAAA2739E485eWindow == null))
                {
                    this.mUIItem590AAAA2739E485eWindow = new UIItem590AAAA2739E485eWindow();
                }
                return this.mUIItem590AAAA2739E485eWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UITutorialHighFrequencWindow mUITutorialHighFrequencWindow;
        
        private UIItem590AAAA2739E485eWindow mUIItem590AAAA2739E485eWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.22609.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'www.hsd.com.a{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "www.hsd.com.a{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.22609.0")]
    public class UITutorialHighFrequencWindow : WinWindow
    {
        
        public UITutorialHighFrequencWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Tutorial: High-Frequency Realtime with SignalR 2 | The ASP.NET Site - Google Chro" +
                "me";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Tutorial: High-Frequency Realtime with SignalR 2 | The ASP.NET Site - Google Chro" +
                    "me");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.22609.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Tutorial: High-Frequency Realtime with SignalR 2 | The ASP.NET Site - Google Chro" +
                    "me");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("Tutorial: High-Frequency Realtime with SignalR 2 | The ASP.NET Site - Google Chro" +
                            "me");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.22609.0")]
    public class UIItem590AAAA2739E485eWindow : WinWindow
    {
        
        public UIItem590AAAA2739E485eWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "{590AAAA2-739E-485e-BF4D-08DDD39C93F6}";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Internet Explorer Server";
            this.WindowTitles.Add("{590AAAA2-739E-485e-BF4D-08DDD39C93F6}");
            #endregion
        }
        
        #region Properties
        public WinClient UIItem590AAAA2739E485eClient
        {
            get
            {
                if ((this.mUIItem590AAAA2739E485eClient == null))
                {
                    this.mUIItem590AAAA2739E485eClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIItem590AAAA2739E485eClient.SearchProperties[WinControl.PropertyNames.Name] = "{590AAAA2-739E-485e-BF4D-08DDD39C93F6}";
                    this.mUIItem590AAAA2739E485eClient.WindowTitles.Add("{590AAAA2-739E-485e-BF4D-08DDD39C93F6}");
                    #endregion
                }
                return this.mUIItem590AAAA2739E485eClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItem590AAAA2739E485eClient;
        #endregion
    }
}
